# Add 'documentation' label to any md file changes
Documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]

# Add 'pages' label to any change within the src/app directory
pages:
  - all:
      - changed-files:
          - any-glob-to-any-file: "src/app/**"

# Add 'components' label to any change to components
components:
  - all:
      - changed-files:
          - any-glob-to-any-file: "src/components/**"

# Add 'services' label to any change to services
services:
  - all:
      - changed-files:
          - any-glob-to-any-file: "src/services/**"

# Add 'helpers' label to any change to helpers
helpers:
  - all:
      - changed-files:
          - any-glob-to-any-file: "src/helpers/**"

# Add 'stores' label to any change to stores
stores:
  - all:
      - changed-files:
          - any-glob-to-any-file: "src/stores/**"

# Add 'workflows' label to any change to github workflows
workflows:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
  - branch: ["^feat", "feature", "feat"]
  - commit-message: ["^feat", "feature", "feat"]

# Add 'bug' label to any PR where the head branch name starts with `bug` or has a `bug` section in the name
bug:
  - branch: ["^bug", "bug"]

# Add 'hotfix' label to any PR where the head branch name starts with `hotfix` or has a `hotfix` section in the name
hotfix:
  - branch: ["^hotfix", "hotfix"]

