name: Jest

on: [pull_request]

jobs:
  jest:
    name: Run jest tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Jest
        run: |
          npm install jest@29.7.0

      - name: Run Jest
        run: TZ=Asia/Dubai npx jest --ci --coverage .
          --config jest.config.ts

      - name: Upload JUnit report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: 'junit.xml'
          github_token: ${{ secrets.PAT }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit.xml

  coverage_report:
    name: Generate coverage report
    needs: jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # ... Generate LCOV files or download it from a different job
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
