name: Jest

on: [pull_request]

jobs:
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  jest:
    name: Run jest tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Jest
        run: |
          npm install jest@29.7.0

      - name: Run Jest
        run: npx jest --ci --coverage .
          --config jest.config.ts

      - name: Upload JUnit report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: 'junit.xml'
          github_token: ${{ secrets.PAT }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit.xml
